name: Bot Cumbuca Eventos

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run bot
        run: python scripts/eventos_reminder.py
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
